#!/usr/bin/env bash

declare -r myname="mitsuke"
echo "The value of the myname variable is : ${myname}"
# myname: readonly variable
myname="NewName"
echo "The value of the myname variable is : ${myname}"


declare -l lowerstring="This is some TEXT!"
echo "The value of the lowerstring variable is : ${lowerstring}"
lowerstring="Let's CHANGE the VALUE!"
echo "The value of the lowerstring variable is : ${lowerstring}"

declare -u upperstring="This is some TEXT!"
echo "The value of the upperstring variable is : ${upperstring}"
upperstring="Let's CHANGE the VALUE!"
echo "The value of the upperstring variable is : ${upperstring}"