#!/usr/bin/env bash

echo "While loop"

declare -i n=0

while (( n < 10))
do
  echo "n:${n}"
  (( n++ ))
done

echo

echo "Until loop"
declare -i m=0
until (( m >= 10 ))
do
  echo "m:${m}"
  (( m++ ))
done
