#!/usr/bin/env bash

arrayToString(){
  local arrayAsString;
  for i in $@
  do
    arrayAsString+=${i}" "
  done
  echo received argument(s) : ${arrayAsString}
}

echo "The $0 script got $# argument(s)"

arrayToString $"$@"
